// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt7rOTx6v5bM2Kcbz4CQD4rNlFcw99Abk',
    appId: '1:902718251964:web:3d5aa8d4a9b5a392ae81b9',
    messagingSenderId: '902718251964',
    projectId: 'flutter-map-1893c',
    authDomain: 'flutter-map-1893c.firebaseapp.com',
    storageBucket: 'flutter-map-1893c.appspot.com',
    measurementId: 'G-ZCP821NCXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6DCUfjTBc1O8iqRAxmQgIwmXwl2nVfDE',
    appId: '1:902718251964:android:3cf573f5fcfa18a5ae81b9',
    messagingSenderId: '902718251964',
    projectId: 'flutter-map-1893c',
    storageBucket: 'flutter-map-1893c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcsJgIQx96P2Fcja_TZTkLqH-B3XGpkeQ',
    appId: '1:902718251964:ios:a82fcceeeb58be4aae81b9',
    messagingSenderId: '902718251964',
    projectId: 'flutter-map-1893c',
    storageBucket: 'flutter-map-1893c.appspot.com',
    iosBundleId: 'com.example.flutterMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcsJgIQx96P2Fcja_TZTkLqH-B3XGpkeQ',
    appId: '1:902718251964:ios:0144789225c02af3ae81b9',
    messagingSenderId: '902718251964',
    projectId: 'flutter-map-1893c',
    storageBucket: 'flutter-map-1893c.appspot.com',
    iosBundleId: 'com.example.flutterMapApp.RunnerTests',
  );
}
